### ISSUE TITLE
hellow，error，why。

### ISSUE THREAD

**Issue by YuzhiSu** [ATATC/PaperCandy#1]
Traceback (most recent call last):
  File "D:\googleDownload\code\A-Deep-Learning-Model-for-Accurate-and-Robust-Internet-Traffic-Classification-master\datasets\tfc2016.py", line 4, in <module>
    from papercandy import *
  File "D:\DLsoftware\Anaconda\envs\traffic01\lib\site-packages\papercandy\__init__.py", line 1, in <module>
    from papercandy.test import *
  File "D:\DLsoftware\Anaconda\envs\traffic01\lib\site-packages\papercandy\test.py", line 4, in <module>
    from papercandy import network as _network
  File "D:\DLsoftware\Anaconda\envs\traffic01\lib\site-packages\papercandy\network.py", line 10, in <module>
    from papercandy.core import network as _network, config as _config
  File "D:\DLsoftware\Anaconda\envs\traffic01\lib\site-packages\papercandy\core\network.py", line 70, in <module>
    class LayerInfoList(object):
  File "D:\DLsoftware\Anaconda\envs\traffic01\lib\site-packages\papercandy\core\network.py", line 80, in LayerInfoList
    def __getitem__(self, item: Union[int, slice]) -> Union[LayerInfo, list[LayerInfo]]:
TypeError: 'type' object is not subscriptable

Process finished with exit code 1

**Comment by ATATC** [comment]
Which version of PaperCandy is it?

**Comment by ATATC** [comment]
Hi YuzhiSu,
What was the main script that you ran?

**Comment by ATATC** [comment]
Hi YuzhiSu!
I've reviewed your Traceback. This is likely to be an error caused by an _incompatible version of Python_. Which version of Python interpreter did you use?
